-- Clear existing sample services and insert real ones
DELETE FROM public.services;

INSERT INTO public.services (name, price, duration, category, active) VALUES
-- Pedicures
('Ice Cream Pedicure Only', 1700, 60, 'Pedicures', true),
('Ice Cream Pedicure With Regular Polish', 2000, 75, 'Pedicures', true),
('Ice Cream Pedicure With Gel Polish', 2550, 90, 'Pedicures', true),
('Ice Cream Pedicure With French Polish', 2600, 90, 'Pedicures', true),
('Algae Pedicure Only', 1800, 60, 'Pedicures', true),
('Algae Pedicure With Regular Polish', 2150, 75, 'Pedicures', true),
('Algae Pedicure With Gel Polish', 2650, 90, 'Pedicures', true),
('Algae Pedicure With French Polish', 2700, 90, 'Pedicures', true),
('Pedicure Only Without Polish', 800, 45, 'Pedicures', true),
('Pedicure With Gel Polish', 1600, 60, 'Pedicures', true),
('Pedicure With French Polish', 1700, 60, 'Pedicures', true),
('Pedicure With Regular Polish', 1050, 60, 'Pedicures', true),
('Spa Pedicure Only', 1500, 60, 'Pedicures', true),
('Spa Pedicure With Gel Polish', 2350, 90, 'Pedicures', true),
('Spa Pedicure With French Polish', 2400, 90, 'Pedicures', true),
('Spa Pedicure With Regular Polish', 1850, 75, 'Pedicures', true),
-- Nail Extensions
('Nail Extension With Gel Polish', 3350, 90, 'Nail Extensions', true),
('Nail Extension With French Gel Polish', 3400, 90, 'Nail Extensions', true),
('Nail Extension With Regular Polish', 2850, 75, 'Nail Extensions', true),
('Nail Extension Only', 2600, 75, 'Nail Extensions', true),
('Toe Nail Extension With French Gel Polish', 3400, 90, 'Nail Extensions', true),
('Toe Nail Extension With Gel Polish', 3350, 90, 'Nail Extensions', true),
('Toe Nail Extension With Regular Polish', 2850, 75, 'Nail Extensions', true),
('Toe Nail Extension Only', 2600, 75, 'Nail Extensions', true),
-- Removals, Refills and Overlay
('Gel Nail Polish Removal', 300, 20, 'Removals, Refills & Overlay', true),
('Extension/Refills/Overlays Removal', 600, 30, 'Removals, Refills & Overlay', true),
('Regular Nail Polish Removal', 100, 10, 'Removals, Refills & Overlay', true),
('Gel Overlay on Natural Nail With French', 2000, 60, 'Removals, Refills & Overlay', true),
('Gel Overlay on Natural Nail With Gel Polish', 1950, 60, 'Removals, Refills & Overlay', true),
('Gel Overlay on Natural Nail With Regular Polish', 1450, 60, 'Removals, Refills & Overlay', true),
('Gel Overlay on Natural Nail Without Polish', 1200, 45, 'Removals, Refills & Overlay', true),
('Gel Nail Extension Refill With French', 2800, 75, 'Removals, Refills & Overlay', true),
('Gel Nail Extension Refill With Gel Polish', 2750, 75, 'Removals, Refills & Overlay', true),
('Gel Nail Extension Refill With Regular Polish', 2250, 60, 'Removals, Refills & Overlay', true),
('Gel Nail Extension Refill Only Without Polish', 2000, 60, 'Removals, Refills & Overlay', true),
-- Manicures
('Manicure With Gel Polish', 1350, 60, 'Manicures', true),
('Manicure With French Gel Polish', 1400, 60, 'Manicures', true),
('Manicure With Regular Polish', 850, 45, 'Manicures', true),
('Manicure Only', 600, 30, 'Manicures', true),
('Spa Manicure With French Gel Polish', 2000, 75, 'Manicures', true),
('Spa Manicure With Gel Polish', 1950, 75, 'Manicures', true),
('Spa Manicure Only', 1200, 60, 'Manicures', true),
('Spa Manicure With Regular Polish', 1450, 60, 'Manicures', true),
('Ice Cream Manicure Only', 1500, 60, 'Manicures', true),
('Ice Cream Manicure With Gel Polish', 2350, 75, 'Manicures', true),
('Ice Cream Manicure With French Polish', 2400, 75, 'Manicures', true),
('Ice Cream Manicure With Regular Polish', 1800, 60, 'Manicures', true),
('Algae Manicure Only', 1600, 60, 'Manicures', true),
('Algae Manicure With Gel Polish', 2450, 75, 'Manicures', true),
('Algae Manicure With French Polish', 2500, 75, 'Manicures', true),
('Algae Manicure With Regular Polish', 1950, 60, 'Manicures', true),
-- Single Nail Series
('Single Big Toe Extension', 700, 20, 'Single Nail Series', true),
('Single Small Toe Extension', 250, 15, 'Single Nail Series', true),
('Single Big Toe Overlay', 375, 15, 'Single Nail Series', true),
('Single Small Toe Overlay Only', 125, 10, 'Single Nail Series', true),
('Single Nail Extension', 350, 15, 'Single Nail Series', true),
('Single Nail French Gel Polish', 80, 10, 'Single Nail Series', true),
('Single Nail Regular Polish', 25, 5, 'Single Nail Series', true),
('Single Nail Gel Polish', 75, 10, 'Single Nail Series', true),
('Single Nail Extension/Overlay/Refill Removal', 60, 10, 'Single Nail Series', true),
('Single Gel Nail Polish Removal', 30, 5, 'Single Nail Series', true),
('Single Nail Overlay', 150, 10, 'Single Nail Series', true),
('Refill With French', 300, 20, 'Single Nail Series', true),
('Refill With Gel Polish', 250, 15, 'Single Nail Series', true),
('Refill With Regular Polish', 180, 15, 'Single Nail Series', true),
-- Nail Polish Applications
('Gel Polish Application', 750, 30, 'Nail Polish Applications', true),
('French Gel Polish Application', 800, 35, 'Nail Polish Applications', true),
('Regular Nail Polish Application', 250, 15, 'Nail Polish Applications', true),
-- Nail Art
('Nail Art (per finger)', 60, 10, 'Nail Art', true),
-- Dry Nourishments
('Dry Pedicure Only', 300, 30, 'Dry Nourishments', true),
('Dry Pedicure With Gel Polish', 1050, 45, 'Dry Nourishments', true),
('Dry Pedicure With French Gel Polish', 1100, 45, 'Dry Nourishments', true),
('Dry Pedicure With Regular Polish', 550, 35, 'Dry Nourishments', true),
('Cut and File Without Pedicure', 250, 20, 'Dry Nourishments', true),
('Dry Manicure Only Without Polish', 250, 20, 'Dry Nourishments', true),
('Dry Manicure With Gel Polish', 1000, 40, 'Dry Nourishments', true),
('Dry Manicure With Regular Polish', 500, 30, 'Dry Nourishments', true),
('Dry Manicure With French Gel Polish', 1050, 40, 'Dry Nourishments', true),
('Cut and File Without Manicure', 250, 20, 'Dry Nourishments', true);
